### ISSUE TITLE
Issue with 'verlet coefficient'

### ISSUE THREAD

**Issue by 1220344230** [msolids/musen#9]
Hi I've recently been using musen for DEM simulations and I've noticed that my models run out differently at different 'verlet coefficients'(without auto adjust verlet distance). Is there any problem with this please?

**Comment by vasylskorych** [comment]
Hi, 
How different are those results? Do the results of two consequent simulations with the **same** Verlet coefficient are the same? What are the values of Verlet coeffcients used? 
In general, due to parallelization mechanisms, MUSEN does not produce exactly the same results - we expect some variations even without changing of any settings of the scene.

**Comment by 1220344230** [comment]
The same coefficients give almost the same results. However, the difference between the results of different coefficients in the simulation in 1s varies from 10% to 20%, and I use coefficients 1, 2 and 3.

**Comment by 1220344230** [comment]
![differ](https://github.com/msolids/musen/assets/109838937/b9f5a0d4-ca19-477b-b453-6cf3008c8ba9)

**Comment by vasylskorych** [comment]
Hi, to be honest, I don't see a strightforward way how Verlet Coefficient alone can influence the simulation behaviour. It is basically a multiplier that is used to calculate the distance around each particle, for which possible collision partners are stored for several next simulation steps. 
What models do you use? CPU or GPU? What are the differences between the largest and smallest particles in the simulation? Did you enable Contact Radius in Scene Editor?
